CREATE TABLE IF NOT EXISTS user_shipping_profiles (
  user_id INT PRIMARY KEY,
  first_name VARCHAR(100) NOT NULL DEFAULT '',
  last_name VARCHAR(100) NOT NULL DEFAULT '',
  email VARCHAR(150) NOT NULL DEFAULT '',
  phone VARCHAR(20) NOT NULL DEFAULT '',
  address TEXT NOT NULL,
  address_line2 VARCHAR(255) DEFAULT NULL,
  subdistrict VARCHAR(100) DEFAULT NULL,
  district VARCHAR(100) NOT NULL DEFAULT '',
  province VARCHAR(100) NOT NULL DEFAULT '',
  postal_code VARCHAR(10) NOT NULL DEFAULT '',
  delivery_note TEXT DEFAULT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

ALTER TABLE customers
  ADD COLUMN IF NOT EXISTS address_line2 VARCHAR(255) DEFAULT NULL AFTER address,
  ADD COLUMN IF NOT EXISTS subdistrict VARCHAR(100) DEFAULT NULL AFTER address_line2,
  ADD COLUMN IF NOT EXISTS delivery_note TEXT DEFAULT NULL AFTER postal_code;

ALTER TABLE orders
  ADD COLUMN IF NOT EXISTS promptpay_qr_url VARCHAR(500) DEFAULT NULL AFTER omise_source_id;
